# docker-compose.yml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-network

  dotnet-builder:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: dotnet-builder
    volumes:
      - ./project:/app
    working_dir: /app
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge